
package pe.Ventas;

import java.util.List;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "VentasDao", targetNamespace = "http://Ventas.pe/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface VentasDao {


    /**
     * 
     * @param arg2
     * @param arg1
     * @param arg0
     * @return
     *     returns java.util.List<java.lang.String>
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "detalleventa", targetNamespace = "http://Ventas.pe/", className = "pe.Ventas.Detalleventa")
    @ResponseWrapper(localName = "detalleventaResponse", targetNamespace = "http://Ventas.pe/", className = "pe.Ventas.DetalleventaResponse")
    @Action(input = "http://Ventas.pe/VentasDao/detalleventaRequest", output = "http://Ventas.pe/VentasDao/detalleventaResponse")
    public List<String> detalleventa(
        @WebParam(name = "arg0", targetNamespace = "")
        int arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        String arg1,
        @WebParam(name = "arg2", targetNamespace = "")
        String arg2);

}
