
package pe.Ventas;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "VentasImpService", targetNamespace = "http://Ventas.pe/", wsdlLocation = "http://localhost:1416/Ventas?wsdl")
public class VentasImpService
    extends Service
{

    private final static URL VENTASIMPSERVICE_WSDL_LOCATION;
    private final static WebServiceException VENTASIMPSERVICE_EXCEPTION;
    private final static QName VENTASIMPSERVICE_QNAME = new QName("http://Ventas.pe/", "VentasImpService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://localhost:1416/Ventas?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        VENTASIMPSERVICE_WSDL_LOCATION = url;
        VENTASIMPSERVICE_EXCEPTION = e;
    }

    public VentasImpService() {
        super(__getWsdlLocation(), VENTASIMPSERVICE_QNAME);
    }

    public VentasImpService(WebServiceFeature... features) {
        super(__getWsdlLocation(), VENTASIMPSERVICE_QNAME, features);
    }

    public VentasImpService(URL wsdlLocation) {
        super(wsdlLocation, VENTASIMPSERVICE_QNAME);
    }

    public VentasImpService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, VENTASIMPSERVICE_QNAME, features);
    }

    public VentasImpService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public VentasImpService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns VentasDao
     */
    @WebEndpoint(name = "VentasImpPort")
    public VentasDao getVentasImpPort() {
        return super.getPort(new QName("http://Ventas.pe/", "VentasImpPort"), VentasDao.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns VentasDao
     */
    @WebEndpoint(name = "VentasImpPort")
    public VentasDao getVentasImpPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://Ventas.pe/", "VentasImpPort"), VentasDao.class, features);
    }

    private static URL __getWsdlLocation() {
        if (VENTASIMPSERVICE_EXCEPTION!= null) {
            throw VENTASIMPSERVICE_EXCEPTION;
        }
        return VENTASIMPSERVICE_WSDL_LOCATION;
    }

}
